print_info() {

    info title
    prin ""

    prin "   (\\ /)"
    prin "   ( . .)"
    prin " c(\")(\")"

    prin ""

    info "wm" wm
    info "os" distro
    info "up" uptime
    info "sh" shell

    prin ""
    prin "       "
}
image_backend="off"
ascii="off"
ascii_distro="none"
