local M = {}

M.lines = function()
    local d = os.date("%dth %B %Y, %H:%M")
    return {
        "/****************************************************",
        "*                                                  *",
        "        author :  siddhantDeshwal                 ",
        "        date   : " .. d .. "           ",
        "*                                                  *",
        "****************************************************/",
        "",
        "#include <algorithm>",
        "#include <chrono>",
        "#include <climits>",
        "#include <cmath>",
        "#include <cstring>",
        "#include <iostream>",
        "#include <map>",
        "#include <queue>",
        "#include <set>",
        "#include <string>",
        "#include <unordered_map>",
        "#include <vector>",
        "",
        "using namespace std;",
        "using ll = signed long long int;",
        "",
        "struct custom_hash {",
        "  static uint64_t splitmix64(uint64_t x) {",
        "    x += 0x9e3779b97f4a7c15;",
        "    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9;",
        "    x = (x ^ (x >> 27)) * 0x94d049bb133111eb;",
        "    return x ^ (x >> 31);",
        "  }",
        "  size_t operator()(uint64_t x) const {",
        "    static const uint64_t FIXED_RANDOM = chrono::steady_clock::now().time_since_epoch().count();",
        "    return splitmix64(x + FIXED_RANDOM);",
        "  }",
        "};",
        "",
        "ll isqrt(ll x) { ll val = sqrtl(x) + 5; while (val*val > x) val--; return val; };",
        "const ll M = 1e9 + 7;",
        "",
        "#define ff first",
        "#define ss second",
        "#define pb push_back",
        "#define fl(i,s,e) for (int i = s; i < e; i++)",
        "#define rfl(i,s,e) for (int i = s; i >= e; i--)",
        "#define all(v) v.begin(), v.end()",
        "#define int long long",
        "",
        "typedef vector<ll> vll;",
        "typedef unordered_map<ll,ll,custom_hash> safehash;",
        "typedef vector<vector<int>> mat;",
        "",
        "void solve() {",
        "    ",
        "}",
        "",
        "int32_t main() {",
        "  ios_base::sync_with_stdio(false);",
        "  cin.tie(NULL);",
        "  int t = 1; cin >> t;",
        "  while (t--) solve();",
        "  return 0;",
        "}",
    }
end

-- cursor: after insert, jump to solve() body
M.cursor_offset = -9 -- lines from bottom to land inside solve()

return M
