# ---------------------------
# Foot Terminal Configuration
# ---------------------------

include=~/.config/foot/themes/hyper

[main]

shell=/usr/bin/fish

font=BlexMono Nerd Font:size=15
font-bold=BlexMono Nerd Font:style=Bold:size=15
font-italic=BlexMono Nerd Font:style=Italic:size=15
font-bold-italic=BlexMono Nerd Font:style=Bold Italic:size=15

pad=7x0


[cursor]
style=block
unfocused-style=hollow

